from django.db import migrations, models
import django.core.validators
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(name='Category', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')), ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Адрес'))], options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории', 'ordering': ('name',)}),
        migrations.CreateModel(name='Pizza', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('name', models.CharField(max_length=150, verbose_name='Название')), ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Адрес')), ('description', models.TextField(verbose_name='Описание')), ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')), ('weight', models.PositiveIntegerField(default=500, verbose_name='Вес, г')), ('image_url', models.URLField(blank=True, verbose_name='Ссылка на изображение')), ('is_available', models.BooleanField(default=True, verbose_name='В продаже')), ('is_popular', models.BooleanField(default=False, verbose_name='Популярная')), ('created_at', models.DateTimeField(auto_now_add=True)), ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pizzas', to='pizza_hanz.category', verbose_name='Категория'))], options={'verbose_name': 'Пицца', 'verbose_name_plural': 'Пиццы', 'ordering': ('-is_popular', 'name')}),
        migrations.CreateModel(name='Order', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('customer_name', models.CharField(max_length=120, verbose_name='Имя')), ('phone', models.CharField(max_length=30, verbose_name='Телефон')), ('address', models.CharField(max_length=250, verbose_name='Адрес')), ('comment', models.TextField(blank=True, verbose_name='Комментарий')), ('status', models.CharField(choices=[('new', 'Новый'), ('cooking', 'Готовится'), ('delivery', 'В доставке'), ('done', 'Выполнен'), ('cancelled', 'Отменён')], default='new', max_length=20, verbose_name='Статус')), ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма')), ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан'))], options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы', 'ordering': ('-created_at',)}),
        migrations.CreateModel(name='OrderItem', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')), ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')), ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pizza_hanz.order')), ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pizza_hanz.pizza', verbose_name='Пицца'))], options={'verbose_name': 'Позиция заказа', 'verbose_name_plural': 'Позиции заказа'}),
    ]
